### ISSUE TITLE
Error creating cluster with custom storage settings 

### ISSUE THREAD

**Issue by Wolfeg** [hyperspike/valkey-operator#126]
i'm trying to create cluster with this example spec:
```yml
apiVersion: hyperspike.io/v1
kind: Valkey
metadata:
  name: valkey-cluster
  namespace: default
spec:
  nodes: 1
  prometheus: true
  volumePermissions: true
  tls: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  storage:
    apiVersion: v1
    kind: PersistentVolumeClaim
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
      storageClassName: my-storage-class
      volumeMode: Filesystem
```
but getting error:
```
2024-11-27T22:17:54Z	ERROR	Observed a panic	{"controller": "valkey", "controllerGroup": "hyperspike.io", "controllerKind": "Valkey", "Valkey": {"name":"valkey","namespace":"rc"}, "namespace": "rc", "name": "valkey", "reconcileID": "fc1681d8-33d0-4d21-b908-676e0ab49335", "panic": "assignment to entry in nil map", "panicGoValue": "\"assignment to entry in nil map\"", "stacktrace": "goroutine 55 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x2df5418, 0xc002438570}, {0x28c4740, 0x2dd3e60})\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.31.3/pkg/util/runtime/runtime.go:107 +0x116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1()\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:105 +0x1fa\npanic({0x28c4740?, 0x2dd3e60?})\n\t$GOROOT/src/runtime/panic.go:785 +0x136\nhyperspike.io/valkey-operator/internal/controller.generatePVC(_)\n\tinternal/controller/valkey_controller.go:1734 +0x40c\nhyperspike.io/valkey-operator/internal/controller.(*ValkeyReconciler).upsertStatefulSet(0xc000482d20, {0x2df5418, 0xc002438570}, 0xc00259a380)\n\tinternal/controller/valkey_controller.go:1821 +0x38f\nhyperspike.io/valkey-operator/internal/controller.(*ValkeyReconciler).Reconcile(0xc000482d20, {0x2df5418, 0xc002438570}, {{{0xc000276856, 0x2}, {0xc000276850, 0x6}}})\n\tinternal/controller/valkey_controller.go:191 +0xd4f\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0x2dff940, {0x2df5418, 0xc002438570}, {{{0xc000276856, 0x2}, {0xc000276850, 0x6}}})\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:116 +0x203\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x2dff940, {0x2df5418, 0xc002438570}, {{{0xc000276856, 0x2}, {0xc000276850, 0x6}}})\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:303 +0x438\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x2dff940, {0x2df5450, 0xc0003f7c70})\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:263 +0x4e6\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2()\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:224 +0xf4\ncreated by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2 in goroutine 120\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:220 +0x9ba\n"}
hyperspike.io/valkey-operator/internal/controller.generatePVC
	internal/controller/valkey_controller.go:1734
hyperspike.io/valkey-operator/internal/controller.(*ValkeyReconciler).upsertStatefulSet
	internal/controller/valkey_controller.go:1821
hyperspike.io/valkey-operator/internal/controller.(*ValkeyReconciler).Reconcile
	internal/controller/valkey_controller.go:191
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:116
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:303
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:263
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.2/pkg/internal/controller/controller.go:224
```
i'm not sure, but i think problem that [here](https://github.com/hyperspike/valkey-operator/blob/main/internal/controller/valkey_controller.go#L1734) should be `:=` instead of `=`
