### ISSUE TITLE
How do I set a storageClass name for my Valkey CRD instance?

### ISSUE THREAD

**Issue by qdrddr** [hyperspike/valkey-operator#180]
Is it something like 

```yaml
spec:
  storage:
    storageClassName: "vsphere"
```

full example:
```yaml
apiVersion: hyperspike.io/v1
kind: Valkey
metadata:
  labels:
    app.kubernetes.io/name: valkey-operator
    app.kubernetes.io/managed-by: kustomize
  name: valkey-db1
spec:
  certIssuerType: ClusterIssuer
  clusterDomain: cluster.local
  nodes: 3
  prometheus: false
  replicas: 0
  tls: false
  volumePermissions: true
  servicePassword:
    name: valkey-db1
    key: password
  storage:
    storageClassName: "vsphere"
```

**Comment by qdrddr** [comment]
For some reason, I cannot apply `storageClassName: "vsphere"` to `storage` @dmolik 
My CR manifest keeps `storage: {}`

**Comment by dmolik** [comment]
As written the operator doesn't have a default storage size, so when you specify a customer storage block it expects you to also specify the disk size. I'm not in front of my computer ATM, I'll get to the bottom of this as soon as I can.

**Comment by qdrddr** [comment]
I do not see it in the CRD `size` fyi.

**Comment by dmolik** [comment]
right, however I simply lifted the PVC Claim Object from the Kubernetes API so it looks like:

```yaml
apiVersion: hyperspike.io/v1
kind: Valkey
metadata:
  name: kv
spec:
  nodes: 3
  volumePermissions: true
  prometheus: false
  tls: false
  storage:
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

```

**Comment by qdrddr** [comment]
So it should look like this, right?
```yaml
apiVersion: hyperspike.io/v1
kind: Valkey
metadata:
  labels:
    app.kubernetes.io/name: valkey-operator
    app.kubernetes.io/managed-by: kustomize
  name: valkey-db1
spec:
  certIssuerType: ClusterIssuer
  clusterDomain: cluster.local
  nodes: 3
  prometheus: false
  replicas: 0
  tls: false
  volumePermissions: true
  servicePassword:
    name: valkey-db1
    key: password
  storage:
    spec:
      storageClassName: "vsphere"
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
```
