### ISSUE TITLE
replica behavior

### ISSUE THREAD

**Issue by travisghansen** [hyperspike/valkey-operator#186]
With this configuration what should the behavior be?

```
apiVersion: hyperspike.io/v1
kind: Valkey
  name: valkey
spec:
  nodes: 1
  replicas: 2
```

I have 3 pods (0-2), all of them show `role:master` and I don't see any replication happening among members.
