### ISSUE TITLE
Valkey manifest ignores servicePassword.name

### ISSUE THREAD

**Issue by drengskapr** [hyperspike/valkey-operator#190]
Hello there! Looks like Valkey manifest ignores servicePassword.name. Here is my config:

```
apiVersion: hyperspike.io/v1
kind: Valkey
metadata:
  labels:
    app.kubernetes.io/name: valkey-operator
  name: valkey-bedroom
  namespace: valkey
spec:
  nodes: 3
  replicas: 0
  prometheus: false
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 512Mi
  servicePassword:
    key: password
    name: valkey-bedroom-secret
  storage:
    apiVersion: v1
    kind: PersistentVolumeClaim
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: "openebs-single-replica"
      volumeMode: Filesystem
  volumePermissions: true
  tls: false
```
my `servicePassword.name` is `valkey-bedroom-secret`. Manifest of my secret is the following:

```
apiVersion: v1
kind: Secret
metadata:
  name: valkey-bedroom-secret
  namespace: valkey
data:
  password: cjh5Zm13ZUJLN1RYR01SMkZzUDUzQQ==
``` 

so it exists within the same `valkey` namespace and completely valid. But when I deploy the cluster manifest I get the following error:

```
Error: secret "valkey-bedroom" not found
```
Definitely Valkey is looking for the secret which matches the cluster name, ignoring provided settings. If I create a secret with the same name as the cluster and set `servicePassword.name` to match with the cluster name and the secret name then everything works fine.

Is there a way to fix this behavior?

**Comment by dmolik** [comment]
fixed with release `v0.0.54`

**Comment by inola-ww** [comment]
Tested with 0.0.57

pod contains wrong secret:

```
        - name: REDISCLI_AUTH
          valueFrom:
            secretKeyRef:
              key: password
              name: backoffice-cache
        - name: VALKEY_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: backoffice-cache
```

```
apiVersion: hyperspike.io/v1
kind: Valkey
metadata:
  name: backoffice-cache
spec:
  nodes: 1
  replicas: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 512Mi
  servicePassword:
    key: password
    name: cache-secret
  storage:
    apiVersion: v1
    kind: PersistentVolumeClaim
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: longhorn
      volumeMode: Filesystem
  volumePermissions: true
  tls: false
```
