### ISSUE TITLE
Controller observed a panic: index out of range [0] with length 0

### ISSUE THREAD

**Issue by inola-ww** [hyperspike/valkey-operator#191]
operator installed via kustomize from https://github.com/hyperspike/valkey-operator/releases/download/v0.0.53/install.yaml

Kubernetes Version: v1.30.5 +k3s1 (on K3s)

**Error**:

runtime error: index out of range [0] with length 0
at
hyperspike.io/valkey-operator/internal/controller.(*ValkeyReconciler).initCluster
	internal/controller/valkey_controller.go:569

Log:

```
2025-02-11T06:38:22Z	ERROR	Observed a panic	{"controller": "valkey", "controllerGroup": "hyperspike.io", "controllerKind": "Valkey", "Valkey": {"name":"backoffice-cache","namespace":"backoffice"}, "namespace": "backoffice", "name": "backoffice-cache", "reconcileID": "20794660-0d69-4e06-8803-aa94c693fcc6", "panic": "runtime error: index out of range [0] with length 0", "panicGoValue": "runtime.boundsError{x:0, y:0, signed:true, code:0x0}", "stacktrace": "goroutine 80 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x2f1f958, 0xc001106210}, {0x2b62c40, 0xc000e46258})\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.32.1/pkg/util/runtime/runtime.go:107 +0x116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1()\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.1/pkg/internal/controller/controller.go:107 +0x1fa\npanic({0x2b62c40?, 0xc000e46258?})\n\t$GOROOT/src/runtime/panic.go:785 +0x136\nhyperspike.io/valkey-operator/internal/controller.(*ValkeyReconciler).initCluster(0xc00037e810, {0x2f1f958, 0xc001106210}, 0xc000506fc0)\n\tinternal/controller/valkey_controller.go:569 +0x2fca\nhyperspike.io/valkey-operator/internal/controller.(*ValkeyReconciler).Reconcile(0xc00037e810, {0x2f1f958, 0xc001106210}, {{{0xc000529100, 0xa}, {0xc0005290f0, 0x10}}})\n\tinternal/controller/valkey_controller.go:203 +0xdd1\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0x2f2d9c0, {0x2f1f958, 0xc001106210}, {{{0xc000529100, 0xa}, {0xc0005290f0, 0x10}}})\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.1/pkg/internal/controller/controller.go:118 +0x203\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x2f2d9c0, {0x2f1f958, 0xc001106210}, {{{0xc000529100, 0xa}, {0xc0005290f0, 0x10}}})\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.1/pkg/internal/controller/controller.go:328 +0x438\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x2f2d9c0, {0x2f1f990, 0xc00016bd60})\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.1/pkg/internal/controller/controller.go:288 +0x4e6\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2()\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.1/pkg/internal/controller/controller.go:249 +0xf4\ncreated by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2 in goroutine 67\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.1/pkg/internal/controller/controller.go:245 +0xc73\n"}
```

my config: 

```
apiVersion: hyperspike.io/v1
kind: Valkey
metadata:
  labels:
    app: backoffice
    app.kubernetes.io/instance: backoffice
    version: 1.4.3.2426
  name: backoffice-cache
  namespace: backoffice
spec:
  nodes: 1
  replicas: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 512Mi
  storage:
    apiVersion: v1
    kind: PersistentVolumeClaim
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: longhorn
      volumeMode: Filesystem
  tls: false
  volumePermissions: true
```
