### ISSUE TITLE
Reconiler error trying to apply the config

### ISSUE THREAD

**Issue by adamcirillo** [hyperspike/valkey-operator#204]
Hi.

i'm getting a reconciler trying to use the operator see logs and config below. using ver 0.0.5.6
also had to remove

```
  storage:
    labels:
      custome: label
```
from the config template in the docs it said was invaild for the label i left the rest of the config under storage there

[valkey-operator.log](https://github.com/user-attachments/files/18808079/valkey-operator.log)

```
apiVersion: hyperspike.io/v1
kind: Valkey
metadata:
  labels:
    app.kubernetes.io/name: valkey
  name: valkey
  namespace: database
spec:
  # the number of master nodes in the cluster
  nodes: 1
  # the number of replicas per master node
  replicas: 1
  # the resource requests and limits for the Valkey Container
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  # boolean value to enable or disable TLS, cert-manager is required for TLS
  tls: false
  # the cert issuer to use for the Valkey Container
  certIssuer: selfsigned
  # the cert issuer type to use for the Valkey Container (ClusterIssuer or Issuer)
  certIssuerType: ClusterIssuer
  # Enalbe or disable external access to the Valkey Container
  externalAccess:
    # boolean value to enable or disable external access
    enabled: false
  # Volume Permissions ensures that the PVC volume ownership is set to the correct user
  volumePermissions: true
  # the image to use for the Valkey Sidecar Container/Exporter image
  exporterImage: ghcr.io/hyperspike/valkey-sidecar:latest
  # the image to use for the Valkey Container
  image: ghcr.io/hyperspike/valkey:latest
  # Enable or disable the Prometheus metrics endpoint requires servicemonitor crd (proetheus-operator|alloy) to be installed
  prometheus: true
  # the Prometheus metric labels to be used to target the correct prometheus instance
  prometheusLabels:
    prometheus: prometheus
  # the PVC object template to use for the Valkey Containers (corev1.PersistentVolumeClaim is used)
  storage:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: longhorn
```
