### ISSUE TITLE
propose change of cert manager crd api

### ISSUE THREAD

**Issue by jonsch318** [hyperspike/valkey-operator#252]
I would propose to keep the cert-manager api of the CRD in line with the cert-manager spec of a certificate

thus 

```
  # Issuer references are always required.
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
```
or maybe even `certManagerIssuerRef: [...]`

instead of `certIssuer` `certIssuerType`

I think this would result in a cleaner API
